version: '3.7'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./db/scripts/create-schema.sql:/docker-entrypoint-initdb.d/10-create-schema.sql
      - ./db/scripts/tables-datafill.sql:/docker-entrypoint-initdb.d/20-tables-datafill.sql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    environment:
      - PORT=${PORT}
      - DB_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db:db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    links:
      - db:db
    ports:
      - '16543:80'
    env_file:
      - ./.env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
